### ISSUE TITLE
Dependency CDO not available with condo

### ISSUE THREAD

**Issue by nilshempelmann** [climateintelligence/owl#2]
Currently no cdo condo package available ( on mac mashines). 

Needs to recreated

**Comment by nilshempelmann** [comment]
It seems that cdo is only used in function_read in two instances: interpolation (line 548 and 622) and time merging (line 671). Since it is giving problems it could be removed and some alternative library (xarray or xesmf for interpolation) used instead.

**Comment by nilshempelmann** [comment]
@leoncav @cehbrecht 
I excluded CDO. Appropriate functions are out commented for the moment. Let's try without cod ;-)

**Comment by cehbrecht** [comment]
There might be an issue with the conda package of `cdo` ... but it is still supported:
https://anaconda.org/conda-forge/cdo/files
